import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "./contexts.js/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
});

export const metadata = {
  title: "DevPath",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${montserrat.className} antialiased bg-[#05152F]`}
      >
        <AppContextProvider>{children}</AppContextProvider>
      </body>
    </html>
  );
}
